#:schema https://dystroy.org/bacon/.bacon.schema.json

# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "server"
env.CARGO_TERM_COLOR = "always"

# Run clippy on the default target
[jobs.server]
command = ["cargo", "clippy", "--features", "server", "-Zno-index-update", "--offline"]
need_stdout = false

[jobs.web]
command = [
	"cargo",
	"clippy",
	"--features",
	"web",
	"--target",
	"wasm32-unknown-unknown",
	"-Zno-index-update",
	"--offline"
]
need_stdout = false

# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal global prefs.toml file instead.
[keybindings]
# alt-m = "job:my-job"
s = "job:server" # comment this to have 'c' run clippy on only the default target
w = "job:web"    # comment this to have 'c' run clippy on only the default target
